
// PRODUCTS

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';

// CATEGORIES

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_PRODUCTS_WITH_CATEGORIES = 'GET_PRODUCTS_WITH_CATEGORIES';

// CATEGORYPRODUCTS
export const GET_CATEGORIES_SECTION = 'GET_CATEGORIES_SECTION'; 

// CART

export const GET_PRODUCT_USER_CART = 'GET_PRODUCT_USER_CART';
export const POST_ADD_TO_CART = 'POST_ADD_TO_CART';